export type ExamPhase =
  | "IDLE"
  | "SCREEN_SHARE_SETUP"
  | "CAMERA_LOADING"
  | "CAMERA_READY"
  | "RECORDING_STARTED"
  | "FIRST_QUESTION_REQUESTED"
  | "QUESTION_READING"
  | "READY_FOR_LISTEN"
  | "LISTENING"
  | "PROCESSING_ANSWER"
  | "GENERATING_QUESTION"
  | "FINISHED";
